# Generated by Django 2.2.2 on 2020-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
