# Generated by Django 2.2.2 on 2020-06-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prices',
            new_name='product',
        ),
    ]
