# Generated by Django 2.2.2 on 2020-05-29 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
