# Generated by Django 2.2.2 on 2020-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_config_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
