# Generated by Django 2.2.2 on 2020-05-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_config_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='user',
        ),
    ]
