# Generated by Django 2.2.2 on 2020-05-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_config_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='config',
        ),
    ]
