# Generated by Django 2.2.2 on 2020-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
