# Generated by Django 2.2.2 on 2020-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200529_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='user',
        ),
        migrations.AlterField(
            model_name='config',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
