# Generated by Django 2.2.2 on 2020-05-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200529_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='config',
        ),
    ]
