# Generated by Django 2.2.2 on 2020-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('everyday', models.BooleanField(default=False)),
                ('everyweek', models.BooleanField(default=False)),
                ('everymonth', models.BooleanField(default=False)),
            ],
        ),
    ]
