# Generated by Django 2.2.2 on 2020-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='everyday',
            field=models.BooleanField(default=True),
        ),
    ]
