# Generated by Django 2.2.2 on 2019-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_consultant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
